---
language: python
os: linux
dist: bionic

install:
  - pip install cython
  - pip install .[all]

script:
  - pytest energyflow
  - python run_all_examples.py

stages:
  - test

jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

branches:
  except:
    - images
